import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.scss';
import Header from 'components/header/header';

const Home = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Фотостудия Екатеринбург</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header></Header>
			<main className={styles.main}></main>

			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;
